FRONTENDBOOTCAMP-13th/JS-04-404-Not-Found

.github/oneway-test.js
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
PR test
resolves #1
=> PR 테스트 완료했습니다. 껄껄.

index.html
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #2
=> PR 테스트 완료했습니다

testchaeeun.html
=> 📝 테스트파일 생성

src/pages/gacha/gacha.css, src/pages/gacha/gacha.html
=> 💄 Gacha - 반응형 수정

src/pages/dictionary/dictionary.css, src/pages/dictionary/dictionary.html, src/pages/dictionary/dictionary.ts
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #31
=> ✨ 도감 초기화면 및 초기화 기능 추가

src/common/local-storage.ts, src/pages/home/home.ts
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- local-storage.ts의 값들을 함수의 반환값으로 받아 사용하도록 수정
resolves #
=> ♻️ local-storage 값들 함수로 반환하도록 수정

src/common/local-storage.ts, src/pages/town/town.html, src/pages/town/town.ts
- [] 버그 수정
- [] 문서 수정
- playTIme 1초씩 갱신되도록 수정
- town페이지의 user-info 작업 진행
resolves #44
=> ✨ playTime 수정 및 user-info 작업 진행중

src/common/local-storage.ts, src/pages/town/town.css, src/pages/town/town.html, src/pages/town/town.ts
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
user-info 진행중
resolves #
=> 🚧 user-info 영역 작업 진행중

package-lock.json, package.json
=> 🐛 Package 수정

src/common/music.ts, src/common/total-time.ts, src/pages/town/town.ts
- [] 새로운 기능 추가
- [] 문서 수정
- town 페이지 user-info 업데이트 되도록 수정
- total-time 배포를 위한 경로 수정
resolves #
=> 🐛 town 페이지 user-info 업데이트 되도록 수정 / total-time 배포를 위한 경로 수정

package-lock.json
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> 🐛 패키지락 json

package-lock.json, package.json
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> 🐛 locj,json

src/pages/dictionary/dictionary.css, src/pages/dictionary/dictionary.ts
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #67
=> ♻️ 도감페이지 코드 리펙토링1차

src/pages/gacha/gacha.css, src/pages/gacha/gacha.html, src/pages/gacha/gacha.ts, src/pages/gacha/pokecard.ts, src/pages/gacha/three-scene.ts
=> ✨ gacha 수정(음악, 카드, 로컬스토리지)

src/pages/town/town.css, src/pages/town/town.ts
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- red 캐릭터 이동 기능 진행중
- 
resolves #
=> 🚧 red 캐릭터 이동 기능 진행중

src/pages/dictionary/dictionary.css, src/pages/dictionary/dictionary.html, src/pages/dictionary/dictionary.ts
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
resolves #67
=> 🚧 도감 코드 리리펙토링2차차

src/pages/gacha/gacha.html
=> ⚰️ gacha(마크업 수정)

src/pages/town/town.css, src/pages/town/town.html, src/pages/town/town.ts
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
-town페이지 red 움직임 추가(모바일/PC)
resolves #
=> ✨ town페이지 red 움직임 추가(모바일/PC)

index.html, src/styles/main.css
=> ✨ 픽셀 애니메이션으로 메인 캐릭터 변경

src/pages/gacha/gacha.css, src/pages/gacha/gacha.html, src/pages/gacha/pokecard.ts, src/pages/gacha/three-scene.ts
- [] 버그 수정
- [] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
resolves #29
=> ✨ gacha (카드배경 수정, 효과음 수정)

src/pages/gacha/pokecard.ts
=> 🐛 gacha (ts파일 수정)

src/pages/dictionary/dictionary.ts, src/pages/home/home.ts, src/pages/town/town.ts
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
- 도감에서 뒤로 가기하면 home으로 가는 이슈 수정
- 음소거 뒤로 가기했을때 이미지 다른 이슈 수정
resolves #
=> 🐛 뒤로가기 버튼, 음소거 이미지 수정

src/pages/dictionary/dictionary.css, src/pages/dictionary/dictionary.html, src/pages/dictionary/dictionary.ts
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- 도감 페이지 header 영역 수정
- 도감 페이지 몬스터볼 우측 하단 고정되도록 수정
- 도감 페이지 카드 리스트 부분 수정
- 도감 페이지 반응형 수정
resolves #
=> 💄 도감 페이지 수정

src/pages/gacha/gacha.css, src/pages/gacha/gacha.html, src/pages/gacha/gacha.ts
- [] 새로운 기능 추가
- [] 버그 수정
- [] 문서 수정
- gacha 모바일 버튼 영역 수정
resolves #
=> ♻️ gacha 모바일 버튼 영역 수정

src/pages/dictionary/dictionary.css, src/pages/dictionary/dictionary.html
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 도감 페이지 오박사 모달창 버튼 위치 수정
resolves #
=> 💄 도감 페이지 오박사 모달창 버튼 위치 수정

src/pages/gacha/gacha.ts, src/pages/slot/slot.ts
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
- 뒤로가기 버튼 경로 수정
resolves #
=> 🐛 뒤로가기 버튼 경로 수정

src/pages/dictionary/dictionary.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- 도감 커서 스타일 변경
resolves #
=> 💄 도감 커서 스타일 변경

src/pages/slot/slot.css
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- slot 모바일에서 a 버튼 위치 수정
resolves #
=> 💄 slot 모바일에서 a 버튼 위치 수정

src/pages/gacha/gacha.css, src/pages/gacha/gacha.html, src/pages/home/home-animation.ts, src/pages/home/home.css, src/pages/home/home.ts
=> ⚰️ home, gacha (홈 애니수정, 가챠 css 수정)

src/pages/gacha/gacha.css
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
- 가챠 카드 이미지, 문구 틀어짐 수정
resolves #
=> 🐛  가챠 카드 이미지, 문구 틀어짐 수정

src/pages/home/home.ts
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
- home 모바일에서 ball 크기 재설정
resolves #
=> 💄 home 모바일에서 ball 크기 재설정

readme.md
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
=> 🔧 fork test
